baseURL = "/"
title = "Spinnaker"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
# [blackfriday]
# plainIDAnchors = true
# hrefTargetBlank = true
# angledQuotes = false
# latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-70174036-1"

# Language configuration

[languages]
[languages.en]
title = "Spinnaker"
description = "Multi-cloud continuous delivery for the enterprise"
languageName ="English"
# Weight used for sorting.
weight = 1

[markup]
defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
          [markup.goldmark.parser]
            attribute = true
            autoHeadingID = true
            autoHeadingIDType = "github"
        [markup.highlight]
          codeFences = true
          guessSyntax = false
          hl_Lines = ""
          lineNoStart = 1
          lineNos = false
          lineNumbersInTable = true
          noClasses = true
          style = "monokai"
          tabWidth = 4
        [markup.tableOfContents]
          endLevel = 3
          ordered = false
          startLevel = 2
# Everything below this are Site Params
[params]
copyright = 'Copyright © 2020 The Linux Foundation®. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our <a href="https://www.linuxfoundation.org/trademark-usage">Trademark Usage</a> page. Linux is a registered trademark of Linus Torvalds.'
privacy_policy = "http://www.linuxfoundation.org/privacy"
terms_of_use = "http://www.linuxfoundation.org/terms"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.
version = "v1.19"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://example.com"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/spinnaker/spinnaker.io"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/spinnaker/spinnaker"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "011737558837375720776:fsdu1nryfng"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = true

#  Promo Banner variables
[params.promoBanner]
  show = true
  text = "Spinnaker Summit 2022 keynotes and talks now available!"
  ctaLink = "https://www.youtube.com/playlist?list=PL2KXbZ9-EY9QW4vewD7Lk6Mm6PJbWECOM"
  ctaText = "Browse Playlist"
  label = ""



# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
nav_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
# [[params.links.user]]
# 	name = "User mailing list"
# 	url = "https://example.org/mail"
# 	icon = "fa fa-envelope"
#         desc = "Discussion and help from your fellow users"
# [[params.links.user]]
# 	name ="Twitter"
# 	url = "https://example.org/twitter"
# 	icon = "fab fa-twitter"
#         desc = "Follow us on Twitter to get the latest news!"
# [[params.links.user]]
# 	name = "Stack Overflow"
# 	url = "https://example.org/stack"
# 	icon = "fab fa-stack-overflow"
#   desc = "Practical questions and curated answers"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "http://github.com/spinnaker"
	icon = "fab fa-github"
  desc = "Spinnaker on Github"
[[params.links.developer]]
	name = "Slack"
	url = "https://join.slack.com/t/spinnakerteam/shared_invite/zt-7juwxmx0-nQ4Ud4pJcbuPykX3SXwQrg"
	icon = "fab fa-slack"
  desc = "Spinnaker Community on Slack"

[[params.links.developer]]
  name = "Twitter"
  url = "https://twitter.com/spinnakerio"
  icon = "fab fa-twitter"
  desc = "Spinnaker Twitter"

# Additional menu item out
[[menu.main]]
  name = "Blog"
  weight = 4
  url = "https://blog.spinnaker.io/"

[[menu.main]]
  name = "Docs"
  weight = 2
  url = "/docs/"

[[menu.main]]
  name = "Community"
  weight = 3
  url = "/docs/community/"
  
[[menu.main]]
  name = "GitHub"
  weight = 50
  url = "https://github.com/spinnaker"
  pre = "<i class='fab fa-github'></i>"
# Add your release versions here


# baseURL = "/"
# languageCode = "en-us"
# title = "Spinnaker"
# disableKinds = ["taxonomy", "taxonomyTerm"]
# theme = "docsy-master"

# Settings for goldmark markdown processing
# [markup]
#   [markup.goldmark]
#     [markup.goldmark.renderer]
#       unsafe = true

# Image processing configuration.
# [imaging]
# resampleFilter = "CatmullRom" # use standard Box processor for now
# quality = 75
# anchor = "smart"
# disableDate = false
# disableLatLong = false

# main menu
# [[menu.main]]
#   name = "Home"
#   url = "/"
#   weight = 1

# [[menu.main]]
#   name = "Getting Started"
#   url = "/en/getting-started/"
#   weight = 1
#
# [[menu.main]]
#   name = "Docs"
#   url = "/en/docs/"
#   weight = 2
#
# [[menu.main]]
#   name = "Community"
#   url = "/en/docs/community/"
#   weight = 3
#
# [[menu.main]]
#   name = "Blog"
#   url = "https://blog.spinnaker.io/"
#   weight = 4
#
# [permalinks]
#   post = "/:year/:month/:day/:slug/"
#   pages = "/:filename/"
