[build]
publish = "public"
command = "hugo --gc --minify"
functions = "./functions"

[context.production.environment]
HUGO_VERSION = "0.70.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo  --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.70.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo  --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
# functions = "./functions"

[context.deploy-preview.environment]
HUGO_VERSION = "0.70.0"

[context.branch-deploy]
command = "hugo  --gc --minify -b $DEPLOY_PRIME_URL"
# functions = "./functions"

[context.branch-deploy.environment]
HUGO_VERSION = "0.70.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/setup/*"
  to = "/docs/setup/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/guides/*"
  to = "/docs/guides/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/reference/*"
  to = "/docs/reference/:splat"
  status = 301
  force = false
  